version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container-app-name
    volumes:
      - ./web-samples:/var/www/html
    ports:
      - "8000:80"
