version: '3.5'
services:
  app:
    image: devsceuma/docker-php-sqlsrv:7.2-apache
    container_name: container-app-name
    volumes:
      - ./web-samples:/var/www/app
    ports:
      - "8000:8080"
